# Created automatically by Cursor AI (2024-08-24)
# Development infrastructure for Viral Content Machine
version: '3.8'

services:
  # Database
  postgres:
    image: pgvector/pgvector:pg16
    container_name: vcm-postgres
    environment:
      POSTGRES_DB: viral_content_machine
      POSTGRES_USER: vcm_user
      POSTGRES_PASSWORD: vcm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vcm_user -d viral_content_machine"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache & Message Broker
  redis:
    image: redis:7-alpine
    container_name: vcm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Event Bus
  nats:
    image: nats:2-alpine
    container_name: vcm-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: nats-server --jetstream --http_port 8222
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Object Storage (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: vcm-minio
    environment:
      MINIO_ROOT_USER: vcm_minio_user
      MINIO_ROOT_PASSWORD: vcm_minio_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  default:
    name: vcm-network
